### ISSUE TITLE
Question about MSE in model_utils.py

### ISSUE THREAD

**Issue by ericyinyzy** [olly-styles/Dynamic-Trajectory-Predictor#11]
Hi Olly,
Thanks for the repo. I have a question about the MSE implementation in model_utils.py.  In model_utils.py, there is a function: 
<img width="504" alt="mse_function" src="https://user-images.githubusercontent.com/24753786/101232228-5f5bd380-36eb-11eb-8e47-7757eefb5c05.png">.
I think Mean Squared Error can be implemented through `np.diff((outputs - targets) * (outputs - targets))`, but why is the result multiplied by a factor `*2` ?

**Comment by olly-styles** [comment]
Hi,

We want to compute the MSE of the coordinates, rather than the individual values. As the inputs to this function are flattened vectors with both x and y coordinates, the result is multiplied by 2 to get the mean for both x and y components. If we do not multiply by 2, we get the mean of the x-axis errors and y-axis errors, i.e., half of the value we want. 

I agree that this isn't the cleanest way of computing this, but try some examples for yourself and you can see that the math checks out:

GT: (0, 1) 
Prediction: (4, 2)

diff = (4-0) * (4-0) + (2 - 1) * (2-1) = [16, 1]
np.mean(diff) * 2 = 17

17 is the squared difference between (0,1) and (4,2) in euclidean space.
