### ISSUE TITLE
Results for different time horizons

### ISSUE THREAD

**Issue by atanas1054** [olly-styles/Dynamic-Trajectory-Predictor#2]
Hello,

Thank you for the repo. Do you have results for other future time horizons (e.g 2,3,5 seconds)? If not are you willing to provide the code used for the other methods (CA, CV, FPL) so that I can generate them myself?

Also, it will be great if you can provide the code for generating the visualization results from the video?

**Comment by olly-styles** [comment]
Hi,

Thanks for your interest in our repo. We did not conduct experiments for time horizons greater than one second. This is mainly due to the size of the JAAD dataset - videos are typically around 10 seconds long, so there are few samples in which a pedestrian is tracked continually for a long time horizon. The pre-processing stage assumes each pedestrian has been detected for at least 25 frames (just under 2 seconds) 10 for computing features and 15 frames to be forecast. 

If you would like to modify the dataset for larger time horizons, you can modify lines 36 and 37 of_process_bounding_boxes_bdd.py_ (for BDD-100K) and lines 29 and 30 of _process_bounding_boxes_jaad.py_ (for JAAD). 

After the pre-processing, the CV baseline using Equation 2 from the paper. Similarly for CA, but rather by using the acceleration rather than velocity. For FPL, see the repo from the authors: https://github.com/takumayagi/fpl

We are not planning to release the visualization code, sorry. If you are interested in working together, feel free to send an email to o.c.styles@warwick.ac.uk
